image: lorisleiva/laravel-docker:8.0
definitions:
  steps:
    - step: &run-test
        name: Run Unit Tests
        caches:
          - composer
        script:
          - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
          - cp .env.example .env
          - php artisan key:generate
          - php artisan test --parallel --recreate-databases
    #- step: &build-image
     #   name: Build Docker Image
      #  services:
       #   - docker
        #script:
         # - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
          # - docker build --pull -t $CI_REGISTRY_IMAGE:$BITBUCKET_COMMIT .
           # - docker push $CI_REGISTRY_IMAGE:$BITBUCKET_COMMIT

pipelines:
  branches:
    development:
      - step: *run-test
    staging:
      - step: *run-test
      #- step:
       #   <<: *build-image
    master:
      - step: *run-test
      #- step:
       #   <<: *build-image
